# Generated by Django 3.1.5 on 2021-01-15 18:35

from django.db import migrations


def add_data(apps, schema_editor):
    student_model = apps.get_model("hw_12_task_1", "Student")
    student = student_model(first_name="Ivan", last_name="Zuev")
    student.save()

    teacher_model = apps.get_model("hw_12_task_1", "Teacher")
    teacher = teacher_model(first_name="Name", last_name="Surname")
    teacher.save()

    hw_model = apps.get_model("hw_12_task_1", "HomeWork")
    hw = hw_model(
        text="Very difficult HW",
        deadline_date="2021-01-17",
        teacher_id=teacher,
        created_date="2020-12-20",
    )
    hw.save()

    hw_result_model = apps.get_model("hw_12_task_1", "HomeWorkResult")
    hw_result = hw_result_model(
        homework_id=hw,
        student_id=student,
        solution_text="HW done",
        solution_date="2021-01-15",
    )
    hw_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ("hw_12_task_1", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_data)]
