repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
        files: 'isort/.*'
      - id: isort
        files: 'tests/.*'

  - repo: https://gitlab.com/pycqa/flake8/
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bandit
          - flake8-bugbear
          - flake8-builtins
          - flake8-cognitive-complexity
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-import-order
          - flake8-mutable
          - flake8-print
          - flake8-pytest-style
          - flake8-return
        args:
          - "--ignore=S101,S301,S403,W503,W605,E501"
